### PR TITLE
Cqlsh serverless v2

### PR DESCRIPTION
**Pull request by Lorak-mmk**
This PR adds serverless support for CQLSH. It was previosuly merged, but dtests later discovered a bug in python driver. The bug should be fixed now, so let's merge this again.

@fruch As you had more luck reproducing the issue with dtests than us, could you try and run them with this PR to make sure it works now?

Fixes https://github.com/scylladb/scylla-tools-java/issues/317 (again)

### CODE REVIEW

**Comment by fruch** [comment]
> This PR adds serverless support for CQLSH. It was previosuly merged, but dtests later discovered a bug in python driver. The bug should be fixed now, so let's merge this again.
> 
> @fruch As you had more luck reproducing the issue with dtests than us, could you try and run them with this PR to make sure it works now?

i could try it out in Sunday, but mean time run it on scylla-ci to see its passing gating (it was noticed on some of the gating tests)

> 
> Fixes https://github.com/scylladb/scylla-tools-java/issues/317 (again)

**Comment by Lorak-mmk** [comment]
CI passed. @fruch did you have time to run those dtests?

**Comment by fruch** [comment]
> > CI passed. @fruch did you have time to run those dtests?
> 
> Didn't got to it, I'm compiling it now.

I've run locally the two suites that were problematic, and didn't seen the issue:
```
./scripts/run_test.sh --scylla-version=5678  cql_cast_test.py json_test.py
```

**Review by fruch — APPROVED** [review]
LGTM

**Comment by avelanarius** [comment]
pinging @scylladb/scylla-maint for merge

**Pull request merged**
