### PR TITLE
stableloader has buggy -s option fixes #110

### LINKED ISSUE #110: sstableloader has buggy -s option
sstableloader --ssl --alg SunX509  ...
will fail with
Missing argument for option:s

fix is to 
make the argument parameter optional, so add ",true" at the end of https://github.com/scylladb/scylla-tools-java/blob/master/src/java/com/scylladb/tools/BulkLoader.java#L975 addOption function call as the last param

### PR DESCRIPTION
**Pull request by tarzanek**
straightforward ... make -s behave as -v
do I need to run dtest for this?

### CODE REVIEW

**Comment by tarzanek** [comment]
http://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/556/

was started

**Comment by tarzanek** [comment]
@elcallio @haaawk could you please approve and merge?

thnx
L

**Comment by haaawk** [comment]
@avikivity please merge

**Comment by slivne** [comment]
@avikivity / @penberg merge ping

**Comment by penberg** [comment]
Reading the bug description, the fix makes sense.

However, please update the commit message (and pull request description) to something that we can merge. Specifically:

* Describe the problem in the title (something being buggy is not very informative).
* Include (short) explanation of the problem (how you reproduce, for example) in the commit message, how you are fixing it, and why. 
* Make sure "Fixes #110" appears in the text body, not the title.

**Comment by tarzanek** [comment]
@penberg done

**Comment by tarzanek** [comment]
@penberg ping? can this be merged?

**Pull request merged**
