### PR TITLE
dist: do not install build dependencies on build script

### PR DESCRIPTION
**Pull request by syuu1228**
We do not want to install dependencies on package building time,
we want to install it on dbuild container.
So drop package installation from the scripts.

scylladb/scylla#7219

### CODE REVIEW

**Comment by avikivity** [comment]
Note we merge directly to master in tools/java, tools/jmx, and tools/python3 now.

**Comment by avikivity** [comment]
Doesn't build for me:

```console
$ ninja dev
[14/191] NINJA build/dev/seastar/libseastar.a
ninja: Entering directory `build/dev/seastar'
ninja: no work to do.
[16/191] NINJA build/dev/seastar/libseastar_testing.a
ninja: Entering directory `build/dev/seastar'
ninja: no work to do.
[19/191] cd tools/java && ./reloc/build_rpm.sh --reloc-pkg build/scylla-tools-package.tar.gz
FAILED: dist-tools-rpm 
cd tools/java && ./reloc/build_rpm.sh --reloc-pkg build/scylla-tools-package.tar.gz
ln: failed to access 'build/scylla-tools-package.tar.gz': No such file or directory
[20/191] cd tools/java && ./reloc/build_deb.sh --reloc-pkg build/scylla-tools-package.tar.gz
FAILED: dist-tools-deb 
cd tools/java && ./reloc/build_deb.sh --reloc-pkg build/scylla-tools-package.tar.gz
[24/191] cd tools/jmx && ./reloc/build_rpm.sh --reloc-pkg build/scylla-jmx-package.tar.gz
'/home/avi/scylla-maint/tools/jmx/build/redhat/SOURCES/scylla-jmx-package.tar.gz' => '/home/avi/scylla-maint/tools/jmx/build/scylla-jmx-package.tar.gz'
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.p85t22
```

**Comment by penberg** [comment]
@syuu1228 I was about to merge this too, but as @avikivity says, it breaks the build.

**Comment by penberg** [comment]
@syuu1228  The issue seems to be related to the handling of `--reloc-pkg` command line option. After you build the tarball with `reloc/build_reloc.sh` you can reproduce the issue with:

```
$ ../scylla/tools/toolchain/dbuild ./reloc/build_rpm.sh --reloc-pkg build/scylla-tools-package.tar.gz
```

**Comment by syuu1228** [comment]
@avikivity @penberg Sorry, fixed the scripts, tested with `ninja-build dist-tools`.

**Pull request closed without merging**
