### PR TITLE
Backport Zstd compression support

### PR DESCRIPTION
**Pull request by kbr-**
Patch by Dinesh Joshi; Reviewed by Blake Eggleston for CASSANDRA-14482

(cherry picked from commit https://github.com/apache/cassandra/commit/dccf53061a61e7c632669c60cd94626e405518e9)

Fixes scylladb/scylla#8887.

### CODE REVIEW

**Comment by kbr-** [comment]
Range-diff:

```
1:  dccf53061a ! 1:  453b8193ba Add Zstd compressor
    @@ Commit message
     
         Patch by Dinesh Joshi; Reviewed by Blake Eggleston for CASSANDRA-14482
     
    - ## CHANGES.txt ##
    -@@
    - 4.0
    -+ * Add Zstd compressor (CASSANDRA-14482)
    -  * Fix IR prepare anti-compaction race (CASSANDRA-15027)
    -  * Fix SimpleStrategy option validation (CASSANDRA-15007)
    -  * Don't try to cancel 2i compactions when starting anticompaction (CASSANDRA-15024)
    +    (cherry picked from commit dccf53061a61e7c632669c60cd94626e405518e9)
     
      ## build.xml ##
     @@
    +     <property name="test.long.src" value="${test.dir}/long"/>
          <property name="test.burn.src" value="${test.dir}/burn"/>
          <property name="test.microbench.src" value="${test.dir}/microbench"/>
    -     <property name="test.distributed.src" value="${test.dir}/distributed"/>
     +    <property name="test.compression_algo" value="LZ4"/>
          <property name="dist.dir" value="${build.dir}/dist"/>
          <property name="tmp.dir" value="${java.io.tmpdir}"/>
      
     @@
    -           <dependency groupId="org.xerial.snappy" artifactId="snappy-java" version="1.1.2.6"/>
    -           <dependency groupId="org.lz4" artifactId="lz4-java" version="1.4.0"/>
    +           <dependency groupId="org.xerial.snappy" artifactId="snappy-java" version="1.1.1.7"/>
    +           <dependency groupId="net.jpountz.lz4" artifactId="lz4" version="1.3.0"/>
                <dependency groupId="com.ning" artifactId="compress-lzf" version="0.8.4"/>
     +          <dependency groupId="com.github.luben" artifactId="zstd-jni" version="1.3.8-5"/>
    -           <dependency groupId="com.google.guava" artifactId="guava" version="23.3-jre"/>
    +           <dependency groupId="com.google.guava" artifactId="guava" version="18.0"/>
                <dependency groupId="org.hdrhistogram" artifactId="HdrHistogram" version="2.1.9"/>
                <dependency groupId="commons-cli" artifactId="commons-cli" version="1.1"/>
     @@
    @@ build.xml
          <path id="all-test-classes-path">
            <fileset dir="${test.unit.src}" includes="**/${test.name}.java" />
     
    - ## doc/source/architecture/storage_engine.rst ##
    -@@ doc/source/architecture/storage_engine.rst: Commitlogs are an append only log of all mutations local to a Cassandra node. An
    - 
    - *Default Value:* /var/lib/cassandra/commitlog
    - 
    --- ``commitlog_compression``: Compression to apply to the commitlog. If omitted, the commit log will be written uncompressed.  LZ4, Snappy, and Deflate compressors are supported.
    -+- ``commitlog_compression``: Compression to apply to the commitlog. If omitted, the commit log will be written uncompressed. LZ4, Snappy, Deflate and Zstd compressors are supported.
    - 
    - (Default Value: (complex option)::
    - 
    -
      ## doc/source/operating/compression.rst ##
     @@ doc/source/operating/compression.rst: Configuring Compression
      Compression is configured on a per-table basis as an optional argument to ``CREATE TABLE`` or ``ALTER TABLE``. By
      default, three options are relevant:
      
     -- ``class`` specifies the compression class - Cassandra provides three classes (``LZ4Compressor``,
    --  ``SnappyCompressor``, and ``DeflateCompressor`` ). The default is ``LZ4Compressor``.
    +-  ``SnappyCompressor``, and ``DeflateCompressor`` ). The default is ``SnappyCompressor``.
     +- ``class`` specifies the compression class - Cassandra provides four classes (``LZ4Compressor``,
    -+  ``SnappyCompressor``, ``DeflateCompressor`` and ``ZstdCompressor``). The default is ``LZ4Compressor``.
    ++  ``SnappyCompressor``, ``DeflateCompressor`` and ``ZstdCompressor``). The default is ``SnappyCompressor``.
      - ``chunk_length_in_kb`` specifies the number of kilobytes of data per compression chunk. The default is 64KB.
      - ``crc_check_chance`` determines how likely Cassandra is to verify the checksum on each compression chunk during
        reads. The default is 1.0.
    @@ src/java/org/apache/cassandra/io/compress/ZstdCompressor.java (new)
     +}
     
      ## src/java/org/apache/cassandra/schema/CompressionParams.java ##
    -@@ src/java/org/apache/cassandra/schema/CompressionParams.java: import com.google.common.annotations.VisibleForTesting;
    - import com.google.common.base.Objects;
    - import com.google.common.collect.ImmutableMap;
    - 
    --import org.apache.commons.lang3.builder.EqualsBuilder;
    - import org.apache.commons.lang3.builder.HashCodeBuilder;
    - 
    - import org.slf4j.Logger;
     @@ src/java/org/apache/cassandra/schema/CompressionParams.java: public final class CompressionParams
    -         return new CompressionParams(LZ4Compressor.create(Collections.emptyMap()), chunkLength, maxCompressedLength, calcMinCompressRatio(chunkLength, maxCompressedLength), Collections.emptyMap());
    +         return new CompressionParams(LZ4Compressor.create(Collections.emptyMap()), chunkLength, Collections.emptyMap());
          }
      
     +    public static CompressionParams zstd()
    @@ src/java/org/apache/cassandra/schema/CompressionParams.java: public final class
     +    public static CompressionParams zstd(Integer chunkLength)
     +    {
     +        ZstdCompressor compressor = ZstdCompressor.create(Collections.emptyMap());
    -+        return new CompressionParams(compressor, chunkLength, Integer.MAX_VALUE, DEFAULT_MIN_COMPRESS_RATIO, Collections.emptyMap());
    ++        return new CompressionParams(compressor, chunkLength, Collections.emptyMap());
     +    }
     +
    -     public CompressionParams(String sstableCompressorClass, Map<String, String> otherOptions, int chunkLength, double minCompressRatio) throws ConfigurationException
    +     public CompressionParams(String sstableCompressorClass, Integer chunkLength, Map<String, String> otherOptions) throws ConfigurationException
          {
    -         this(createCompressor(parseCompressorClass(sstableCompressorClass), otherOptions), chunkLength, calcMaxCompressedLength(chunkLength, minCompressRatio), minCompressRatio, otherOptions);
    +         this(createCompressor(parseCompressorClass(sstableCompressorClass), otherOptions), chunkLength, otherOptions);
     
      ## test/conf/commitlog_compression.yaml => test/conf/commitlog_compression_LZ4.yaml ##
     
    @@ test/long/org/apache/cassandra/io/compress/CompressorPerformance.java: public cl
      
     
      ## test/unit/org/apache/cassandra/db/RecoveryManagerFlushedTest.java ##
    -@@ test/unit/org/apache/cassandra/db/RecoveryManagerFlushedTest.java: import org.slf4j.LoggerFactory;
    - import org.apache.cassandra.SchemaLoader;
    - import org.apache.cassandra.config.DatabaseDescriptor;
    - import org.apache.cassandra.config.ParameterizedClass;
    +@@ test/unit/org/apache/cassandra/db/RecoveryManagerFlushedTest.java: import org.apache.cassandra.exceptions.ConfigurationException;
    + import org.apache.cassandra.io.compress.DeflateCompressor;
    + import org.apache.cassandra.io.compress.LZ4Compressor;
    + import org.apache.cassandra.io.compress.SnappyCompressor;
     +import org.apache.cassandra.io.compress.ZstdCompressor;
    - import org.apache.cassandra.schema.SchemaConstants;
    - import org.apache.cassandra.db.compaction.CompactionManager;
    - import org.apache.cassandra.db.commitlog.CommitLog;
    + import org.apache.cassandra.schema.KeyspaceParams;
    + import org.apache.cassandra.security.EncryptionContext;
    + import org.apache.cassandra.security.EncryptionContextGenerator;
     @@ test/unit/org/apache/cassandra/db/RecoveryManagerFlushedTest.java: public class RecoveryManagerFlushedTest
                  {null, EncryptionContextGenerator.createContext(true)}, // Encryption
                  {new ParameterizedClass(LZ4Compressor.class.getName(), Collections.emptyMap()), EncryptionContextGenerator.createDisabledContext()},
    @@ test/unit/org/apache/cassandra/db/RecoveryManagerTest.java: import org.apache.ca
      import org.apache.cassandra.io.compress.LZ4Compressor;
      import org.apache.cassandra.io.compress.SnappyCompressor;
     +import org.apache.cassandra.io.compress.ZstdCompressor;
    - import org.apache.cassandra.schema.ColumnMetadata;
    - import org.apache.cassandra.schema.KeyspaceParams;
    - import org.apache.cassandra.security.EncryptionContext;
    + 
    + import org.junit.Assert;
    + import org.junit.Before;
     @@ test/unit/org/apache/cassandra/db/RecoveryManagerTest.java: public class RecoveryManagerTest
                  {null, EncryptionContextGenerator.createContext(true)}, // Encryption
                  {new ParameterizedClass(LZ4Compressor.class.getName(), Collections.emptyMap()), EncryptionContextGenerator.createDisabledContext()},
    @@ test/unit/org/apache/cassandra/db/RecoveryManagerTruncateTest.java: public class
          @Before
     
      ## test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java ##
    -@@ test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java: import org.junit.runners.Parameterized.Parameters;
    - 
    - import org.apache.cassandra.SchemaLoader;
    - import org.apache.cassandra.Util;
    +@@ test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java: import org.apache.cassandra.io.FSWriteError;
    + import org.apache.cassandra.io.compress.DeflateCompressor;
    + import org.apache.cassandra.io.compress.LZ4Compressor;
    + import org.apache.cassandra.io.compress.SnappyCompressor;
     +import org.apache.cassandra.io.compress.ZstdCompressor;
    - import org.apache.cassandra.io.util.FileUtils;
    - import org.apache.cassandra.schema.TableId;
    - import org.apache.cassandra.schema.TableMetadata;
    -@@ test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java: public abstract class CommitLogTest
    + import org.apache.cassandra.io.sstable.format.SSTableReader;
    + import org.apache.cassandra.net.MessagingService;
    + import org.apache.cassandra.schema.KeyspaceParams;
    +@@ test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java: public class CommitLogTest
                  {null, EncryptionContextGenerator.createContext(true)}, // Encryption
                  {new ParameterizedClass(LZ4Compressor.class.getName(), Collections.emptyMap()), EncryptionContextGenerator.createDisabledContext()},
                  {new ParameterizedClass(SnappyCompressor.class.getName(), Collections.emptyMap()), EncryptionContextGenerator.createDisabledContext()},
    @@ test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java: public abstract
     +            {new ParameterizedClass(ZstdCompressor.class.getName(), Collections.emptyMap()), EncryptionContextGenerator.createDisabledContext()}});
          }
      
    -     public static void beforeClass() throws ConfigurationException
    +     @BeforeClass
     
      ## test/unit/org/apache/cassandra/db/commitlog/SegmentReaderTest.java ##
     @@ test/unit/org/apache/cassandra/db/commitlog/SegmentReaderTest.java: import org.apache.cassandra.io.compress.DeflateCompressor;
    @@ test/unit/org/apache/cassandra/io/compress/CQLCompressionTest.java: public class
     +    public void zstdParamsTest()
     +    {
     +        createTable("create table %s (id int primary key, uh text) with compression = {'class':'ZstdCompressor', 'compression_level':-22}");
    -+        assertTrue(((ZstdCompressor)getCurrentColumnFamilyStore().metadata().params.compression.getSstableCompressor()).getClass().equals(ZstdCompressor.class));
    -+        assertEquals(((ZstdCompressor)getCurrentColumnFamilyStore().metadata().params.compression.getSstableCompressor()).getCompressionLevel(), -22);
    ++        assertTrue(((ZstdCompressor)getCurrentColumnFamilyStore().metadata.params.compression.getSstableCompressor()).getClass().equals(ZstdCompressor.class));
    ++        assertEquals(((ZstdCompressor)getCurrentColumnFamilyStore().metadata.params.compression.getSstableCompressor()).getCompressionLevel(), -22);
     +
     +        createTable("create table %s (id int primary key, uh text) with compression = {'class':'ZstdCompressor'}");
    -+        assertTrue(((ZstdCompressor)getCurrentColumnFamilyStore().metadata().params.compression.getSstableCompressor()).getClass().equals(ZstdCompressor.class));
    -+        assertEquals(((ZstdCompressor)getCurrentColumnFamilyStore().metadata().params.compression.getSstableCompressor()).getCompressionLevel(), ZstdCompressor.DEFAULT_COMPRESSION_LEVEL);
    ++        assertTrue(((ZstdCompressor)getCurrentColumnFamilyStore().metadata.params.compression.getSstableCompressor()).getClass().equals(ZstdCompressor.class));
    ++        assertEquals(((ZstdCompressor)getCurrentColumnFamilyStore().metadata.params.compression.getSstableCompressor()).getCompressionLevel(), ZstdCompressor.DEFAULT_COMPRESSION_LEVEL);
     +    }
     +
     +    @Test(expected = ConfigurationException.class)

```

**Comment by elcallio** [comment]
Looks fine to me. Did you have to change anything from the initial cherry-pick, or did it merge smoothly?

**Comment by kbr-** [comment]
There was a minor conflict due to missing https://github.com/apache/cassandra/commit/f97db26f8e9989d2294cccbea8a06589253313f2 causing this part of the range-diff:
```
    @@ src/java/org/apache/cassandra/schema/CompressionParams.java: public final class
     +    public static CompressionParams zstd(Integer chunkLength)
     +    {
     +        ZstdCompressor compressor = ZstdCompressor.create(Collections.emptyMap());
    -+        return new CompressionParams(compressor, chunkLength, Integer.MAX_VALUE, DEFAULT_MIN_COMPRESS_RATIO, Collections.emptyMap());
    ++        return new CompressionParams(compressor, chunkLength, Collections.emptyMap());
     +    }
     +
    -     public CompressionParams(String sstableCompressorClass, Map<String, String> otherOptions, int chunkLength, double minCompressRatio) throws ConfigurationException
    +     public CompressionParams(String sstableCompressorClass, Integer chunkLength, Map<String, String> otherOptions) throws ConfigurationException
          {
    -         this(createCompressor(parseCompressorClass(sstableCompressorClass), otherOptions), chunkLength, calcMaxCompressedLength(chunkLength, minCompressRatio), minCompressRatio, otherOptions);
    +         this(createCompressor(parseCompressorClass(sstableCompressorClass), otherOptions), chunkLength, otherOptions);
```

other than that the backport wasn't very interesting.

**Comment by kbr-** [comment]
And had to change `metadata()` to `metadata` here:
```
     +    public void zstdParamsTest()
     +    {
     +        createTable("create table %s (id int primary key, uh text) with compression = {'class':'ZstdCompressor', 'compression_level':-22}");
    -+        assertTrue(((ZstdCompressor)getCurrentColumnFamilyStore().metadata().params.compression.getSstableCompressor()).getClass().equals(ZstdCompressor.class));
    -+        assertEquals(((ZstdCompressor)getCurrentColumnFamilyStore().metadata().params.compression.getSstableCompressor()).getCompressionLevel(), -22);
    ++        assertTrue(((ZstdCompressor)getCurrentColumnFamilyStore().metadata.params.compression.getSstableCompressor()).getClass().equals(ZstdCompressor.class));
    ++        assertEquals(((ZstdCompressor)getCurrentColumnFamilyStore().metadata.params.compression.getSstableCompressor()).getCompressionLevel(), -22);
     +
     +        createTable("create table %s (id int primary key, uh text) with compression = {'class':'ZstdCompressor'}");
    -+        assertTrue(((ZstdCompressor)getCurrentColumnFamilyStore().metadata().params.compression.getSstableCompressor()).getClass().equals(ZstdCompressor.class));
    -+        assertEquals(((ZstdCompressor)getCurrentColumnFamilyStore().metadata().params.compression.getSstableCompressor()).getCompressionLevel(), ZstdCompressor.DEFAULT_COMPRESSION_LEVEL);
    ++        assertTrue(((ZstdCompressor)getCurrentColumnFamilyStore().metadata.params.compression.getSstableCompressor()).getClass().equals(ZstdCompressor.class));
    ++        assertEquals(((ZstdCompressor)getCurrentColumnFamilyStore().metadata.params.compression.getSstableCompressor()).getCompressionLevel(), ZstdCompressor.DEFAULT_COMPRESSION_LEVEL);
     +    }
```

**Review by haaawk — APPROVED** [review]
LGTM

**Comment by nyh** [comment]
Looks good to me. I'm trying to commit it but want to compile-test it first and I am encountering some setup problems and hopefully soon I'll solve them.

**Comment by kbr-** [comment]
Note: `CommitLogTest` fails for some reason, I tried to run it because the patch modifies it.
However, it also fails on master, I don't think this patchset broke it more than it already was.

**Pull request closed without merging**
