### PR TITLE
merge(enterprise-features): Merge enterprise features

### PR DESCRIPTION
**Pull request by dkropachev**
Merge enterprise features to the next branch:
      Enterprise feature "config encryption", configuration_ecryptor and local_file_key_generator
      Enterprise feature "IncrementalCompationStrategy", needed for c-s

### CODE REVIEW

**Comment by avikivity** [comment]
@dkropachev the commit should explain what it is merging, if it wants to get merged.

Please follow the normal style of core commits, not the dtest style.

**Comment by dkropachev** [comment]
> @dkropachev the commit should explain what it is merging, if it wants to get merged.
> 
> Please follow the normal style of core commits, not the dtest style.

fixed

**Comment by avikivity** [comment]
The patch says what it is doing, but not why. I don't understand why you are doing all that.

**Comment by avikivity** [comment]
In general it's very vad practice for an open source project to partially support features of a proprietary product. Open-source projects should be self-contained.

**Comment by elcallio** [comment]
Why are you merging enterprise tools (encryption stuff) info open source? I don't think we should do that. At best it is useless, and at worst it might make users think the features exist in the os version.

**Comment by dkropachev** [comment]
Ok, i'am closing it

**Pull request closed without merging**
