### PR TITLE
nodetool: fix a typo in error message

### PR DESCRIPTION
**Pull request by tchaikov**
s/smaller then/smaller than/

### CODE REVIEW

**Review by mykaul — APPROVED** [review]

**Comment by tchaikov** [comment]
we need to get https://github.com/scylladb/scylla-dtest/pull/4000 merged before landing this change.

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help merge this change?

**Review by nyh — APPROVED** [review]
This code was written by upstream Cassandra, 9 years ago, I'm not sure if we want to fix spelling mistakes in it in our own branch, but I can't deny is a spelling mistake so if you already have a PR, might as well merge it...

**Comment by nyh** [comment]
I merged this. Now the ugly part begins - I'll create a PR in scylla.git to update the submodule, and we'll see if you're right and dtest (after your patch) didn't break by this change.

**Comment by tchaikov** [comment]
@nyh thank you! yeah. fingers crossed..

**Pull request closed without merging**
