### PR TITLE
nodetool: support validate

### LINKED ISSUE #263: nodetool: add method to invoke validation compaction
Scylla issue for scylla implementation: https://github.com/scylladb/scylla/issues/7736

### PR DESCRIPTION
**Pull request by bhalevy**
Add support for `nodetool validate [ks [cf...]]`
Based on the api added in scylladb/scylla@b0ef57c83390ada3152568f06769ad76c596cb5e

Depends on https://github.com/scylladb/scylla-jmx/pull/173

Fixes #263

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

**Comment by bhalevy** [comment]
Cc @raphaelsc

**Comment by raphaelsc** [comment]
@bhalevy isn't it better to instead extend nodetool scrub with a --dry-run option? so we won't have to come up with yet another tool.

**Comment by bhalevy** [comment]
> @bhalevy isn't it better to instead extend nodetool scrub with a --dry-run option? so we won't have to come up with yet another tool.

It's an interesting approach.

@denesb already opened #268 to support a new, `segregate` scrub mode.
I think it's going to be easier to represent `validate` as an additional scrub mode, rather than adding a `--dry-run` option
See scylladb/scylla@34643ac997.

This will require changing the api that was added in scylladb/scylla@b0ef57c833

**Comment by denesb** [comment]
> @bhalevy isn't it better to instead extend nodetool scrub with a --dry-run option? so we won't have to come up with yet another tool.

I think this would open up a lot of confusion about what `--dry-run` means when any of the other flags are set to any value. IMO "validate" is just a more straightforward name and it also better describes what this really is.

**Comment by raphaelsc** [comment]
On Thu, Jul 29, 2021 at 3:43 AM Botond Dénes ***@***.***>
wrote:

> @bhalevy <https://github.com/bhalevy> isn't it better to instead extend
> nodetool scrub with a --dry-run option? so we won't have to come up with
> yet another tool.
>
> I think this would open up a lot of confusion about what --dry-run means
> when any of the other flags are set to any value. IMO "validate" is just a
> more straightforward name and it also better describes what this really is.
>
Just realized that validation compaction in C* has a different meaning
"During a repair, each replica will build a merkle tree, using what is
called a “validation compaction”. It is basically a compaction without the
write phase, the output being a tree of hashes.". So I think we better
change the name to avoid confusion. What an ambiguous name they come up
with. Not the first though :-) See cleanup command, for example, which is
only intended to remove non-owned data, and received a generic name
misleading users into thinking that the command clean up other things as
well.

With --dry-run, the only difference is that scrub becomes read-only. If one
needs only a binary response, nodetool scrub --dry-run will work. If you
one needs full scope on corruption, then nodetool scrub
--dry-run --skip-corrupted will do it. Default behavior is to validate all
columns.

**Comment by denesb** [comment]
>> On Thu, Jul 29, 2021 at 3:43 AM Botond Dénes ***@***.***> wrote: @bhalevy <https://github.com/bhalevy> isn't it better to instead extend nodetool scrub with a --dry-run option? so we won't have to come up with yet another tool. I think this would open up a lot of confusion about what --dry-run means when any of the other flags are set to any value. IMO "validate" is just a more straightforward name and it also better describes what this really is.
>
> Just realized that validation compaction in C* has a different meaning "During a repair, each replica will build a merkle tree, using what is called a “validation compaction”. It is basically a compaction without the write phase, the output being a tree of hashes.". So I think we better change the name to avoid confusion.

So this was an internal thing, not something user facing, right? If so users are not likely to even know about it and thus be confused.  We don't need to be unambiguous to C* developers :).

**Comment by raphaelsc** [comment]
On Fri, Jul 30, 2021 at 2:45 AM Botond Dénes ***@***.***>
wrote:

> On Thu, Jul 29, 2021 at 3:43 AM Botond Dénes *@*.***> wrote: @bhalevy
> <https://github.com/bhalevy> https://github.com/bhalevy isn't it better
> to instead extend nodetool scrub with a --dry-run option? so we won't have
> to come up with yet another tool. I think this would open up a lot of
> confusion about what --dry-run means when any of the other flags are set to
> any value. IMO "validate" is just a more straightforward name and it also
> better describes what this really is.
>
> Just realized that validation compaction in C* has a different meaning
> "During a repair, each replica will build a merkle tree, using what is
> called a “validation compaction”. It is basically a compaction without the
> write phase, the output being a tree of hashes.". So I think we better
> change the name to avoid confusion.
>
> So this was an internal thing, not something user facing, right? If so
> users are not likely to even know about it and thus be confused. We don't
> need to be unambiguous to C* developers :).
>
VALIDATION will show up in nodetool compactionstats. So there will be this
difference which users will face. C* users will be confused because they
use compactionstats to track validation compactions as defined above.
Perhaps rename the validation string to something more specific to avoid
any sort of confusion?

**Comment by denesb** [comment]
> VALIDATION will show up in nodetool compactionstats. So there will be this difference which users will face. C* users will be confused because they use compactionstats to track validation compactions as defined above. Perhaps rename the validation string to something more specific to avoid any sort of confusion?

I think at that point it is just better to go with `scrub --dry-mode`. @penberg also noted that `nodetool validate` is not present in C*'s nodetool.

**Comment by bhalevy** [comment]
Functionality achieved by https://github.com/scylladb/scylla-tools-java/pull/272 as `nodetool scrub --mode VALIDATE`

**Pull request closed without merging**
