### PR TITLE
Make C* compile and run on Java 11 and Java 8

### PR DESCRIPTION
**Pull request by elcallio**
patch by Robert Stupp; reviewed by Jason Brown for CASSANDRA-9608

reworked for scylla and 3.11 code base.

### CODE REVIEW

**Comment by elcallio** [comment]
Note: Testes in so far as running the daemon + tools + stress etc with both jdk 8 and jdk 11. But on my machine, on my build. 
I would very much suggest merging into a test branch and run whatever set of comprehensive tests you can think of with jdk 11 before fully adopting it.

**Comment by slivne** [comment]
@haaawk - need your help with this one - can you give your blessing - I can try a BYOD run to get some validation as well

**Comment by penberg** [comment]
Unfortunately dtests failed with this commit:

```
22:59:24  OSError: [Errno 8] Exec format error: '/jenkins/workspace/scylla-master/next/scylla/resources/cassandra/bin/sstableloader'
```

and

```
22:59:24  AssertionError: 'grep: /jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-xms448hy/test/node1/conf/jvm-clients.options: No such file or directory\ngrep: /jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-xms448hy/test/node1/conf/jvm8-clients.options: No such file or directory\n' is not false
```

@elcallio Shouldn't the `sstableloader` have have a shebang (`!#"`) directive? Not sure what the client options thing is about.

**Comment by elcallio** [comment]
Original branch updated. I can't seem to re-open this pull, so I created a new one.

**Pull request merged**
